#!/usr/bin/env bash

# Run from .github/workflows/docs.yml
# Rebuild Sphinx docs from scratch and check generated files match those checked
# in

set -euo pipefail

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_ROOT_DIR=${THIS_DIR}/../..
DOCS_DIR=${PROJECT_ROOT_DIR}/docs
VENV_DIR=${HOME}/venv

cd "${PROJECT_ROOT_DIR}"

sudo apt-get install texlive-latex-extra dvipng
PYTHON=${VENV_DIR}/bin/python
echo Installing pip packages for docs
${PYTHON} -m pip install -r "${DOCS_DIR}/docs_requirements.txt"
########################################################################################
echo Creating autodocs
${PYTHON} "${DOCS_DIR}/create_all_autodocs.py" --make --destroy_first
echo Checking if files generated by create_all_autodocs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
echo Rebuilding docs

# Have to be in the virtualenv for sphinx-build to be picked up.
source "${VENV_DIR}"/bin/activate
python "${DOCS_DIR}/rebuild_docs.py" --warnings_as_errors
echo Checking if files generated by rebuild_docs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
