#!/usr/bin/env bash

# Run from .github/workflows/docs.yml
# Rebuild Sphinx docs from scratch and check generated files match those checked
# in

set -euo pipefail

sudo apt-get install texlive-latex-extra dvipng
python -m venv "${HOME}/venv"
PYTHON=${HOME}/venv/bin/python
${PYTHON} -VV
${PYTHON} -m site
${PYTHON} -m pip install -U pip
echo installing pip packages
${PYTHON} -m pip install -r docs/docs_requirements.txt
${PYTHON} -m pip install -e .
########################################################################################
cd "${GITHUB_WORKSPACE}/docs"
echo Creating autodocs
${PYTHON} ./create_all_autodocs.py --make --destroy_first
cd "${GITHUB_WORKSPACE}"
echo Checking if files generated by create_all_autodocs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
cd docs
echo Rebuilding docs
${PYTHON} ./rebuild_docs.py --warnings_as_errors
echo Checking if files generated by rebuild_docs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
