---
# yamllint disable rule:line-length
name: Build docs
# yamllint disable-line rule:truthy
on: push

jobs:
    build-docs:
        strategy:
            matrix:
                include:
                    - name: ubuntu-22.04
                      os: ubuntu-22.04
                      python-version: "3.10"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Create virtualenv
              run: ${GITHUB_WORKSPACE}/.github/scripts/create_virtualenv.sh
            - name: Install base Python packages
              run: ${GITHUB_WORKSPACE}/.github/scripts/install_base_python_packages.sh
            - name: Build docs
              run: ${GITHUB_WORKSPACE}/.github/scripts/build_docs.sh
            - name: Dump stuff on failure
              if: failure()
              run: |
                  set -euxo pipefail
                  ls -l ${HOME}/venv/bin
                  ${HOME}/venv/bin/python -m pip freeze
