---
# yamllint disable rule:line-length
name: Python checks
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/scripts/create_virtualenv.sh
            - .github/scripts/install_base_python_packages.sh
            - .github/scripts/python_checks.sh
            - .github/workflows/python-checks.yml
jobs:
    python-checks:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10"]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Create virtualenv
              run: ${GITHUB_WORKSPACE}/.github/scripts/create_virtualenv.sh
            - name: Install base Python packages
              run: ${GITHUB_WORKSPACE}/.github/scripts/install_base_python_packages.sh
            - name: Python checks
              run: ${GITHUB_WORKSPACE}/.github/scripts/python_checks.sh
