---
# yamllint disable rule:line-length
name: Run tests
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/scripts/change_apt_mirror.sh
            - .github/scripts/create_virtualenv.sh
            - .github/scripts/install_base_python_packages.sh
            - .github/scripts/install_test_python_packages.sh
            - .github/scripts/run_tests.sh
            - .github/workflows/run_tests.yml
jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10"]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Change apt mirror
              run: ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
            - name: Create virtualenv
              run: ${GITHUB_WORKSPACE}/.github/scripts/create_virtualenv.sh
            - name: Install test Python packages
              run: ${GITHUB_WORKSPACE}/.github/scripts/install_test_python_packages.sh
            - name: Install base Python packages
              run: ${GITHUB_WORKSPACE}/.github/scripts/install_base_python_packages.sh
            - name: Run tests
              run: ${GITHUB_WORKSPACE}/.github/scripts/run_tests.sh
