---
# yamllint disable rule:line-length
name: Tests
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/workflows/run_tests.yml
            - .github/scripts/run_tests.sh
jobs:
    pip-install-and-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10.0"]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Run tests
              run: ${GITHUB_WORKSPACE}/.github/scripts/run_tests.sh
